apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-longhorn-config
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  path: ./clusters/hlcl1/infra/storage/longhorn/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-longhorn
  timeout: 5m
