apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ff-postgres
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  path: ./clusters/hlcl1/infra/databases/postgres/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-shared-namespaces
    - name: infra-cloudnativepg
  wait: true
  timeout: 10m
