apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
stringData:
    adminPassword: ENC[AES256_GCM,data:glDDCH6//Z15WIj/n/WA+bScdTQ=,iv:UWm8HXgsYslsBiM2gZWUAeF8HeGoDPVvrZ+Bmx+OaZ8=,tag:qS0lgKwjq/IiJmmKbz0f+A==,type:str]
sops:
    age:
        - recipient: age1yvyefwwh6avrzpkz2vr3w86ly6q97hdpz02jns2yvaafnjnv448s7jdx7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxLzNxRGxSMUtEWEZYTlNt
            WWZYOXRiMEFoZWpRQlpPREFWZk80d2JFQVNJCnRRUXVCbDhkK09FSHIxVkZaandC
            QnJZSUQvd201MWZNUS9XVHRlZmRSeWMKLS0tIHgwVEFyQklMN29YZXFtZ3gzZXky
            MFRLRElZcjU5K2UyZ0k0M2ttQnNWaVkKWDEkAOpdnFMUwVOAgN95YpMSZQHzkYsM
            mT8SaK9PrjONsRKSFL8mC5TkxpkeiZA710VwQerBuAUpFq35byeU3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T08:39:20Z"
    mac: ENC[AES256_GCM,data:lHDp6v/A4dxz4EPzWTv+CCLv1ybY0OKIuZ2gkfZvGsMKbmdKjl8ZEYvvzwljuu/8h9WyvEVy/qOvz0JqPWSgJQvaXvq1CHrXFa4d6PVS0EmBNAQjK6VAoUetXTLp5mmtaHZkpm33WvzKyQMEzJUnlEcYRR6rmZH91IegQrN9lAM=,iv:i5VwGcIbUIxl90PnCjOrXDfX76tjfetYr+UfK+q86Cw=,tag:kQwj09v1vAv6sCKR65y9DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
