apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/storage/longhorn
  - infra/storage/nfs
  - infra/network/metallb
  - infra/secrets/external-secrets
  - infra/shared-namespaces
  - infra/databases
  - apps/pihole
  - apps/monitoring
