apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Qpkj7Pc=,iv:T35fU6QNkHh/2B6b7INzM9CdVSu8IGcI01HKK44XZ1U=,tag:KqNZ0CQ40JbflD48eZUsoA==,type:str]
    admin-password: ENC[AES256_GCM,data:0+mVZv+gXCzs4+wIK3eQpo1edmI=,iv:ixbGv9biaKzGBBCU0jaouRUFVIr8InC37tuU+iJt1+U=,tag:FF/bR2Dk+RGB3AJGEuuUGg==,type:str]
sops:
    age:
        - recipient: age1yvyefwwh6avrzpkz2vr3w86ly6q97hdpz02jns2yvaafnjnv448s7jdx7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabURhT2dmVmZPVGE4ME9Y
            dTVhcHJRNXFQN0pYcVFiM0tVRXk5bmVseUF3CktzRGFaZEFNNDRpckRLMFhwL1VW
            b1k1cUVGTGJiTFpnRlh1WkRURHRoSzQKLS0tIEZFTGdRUjIwMG5qRkNuVXFTWFE4
            R0E4ZGxqck93N2RrLzVuQ1poTUMzeGMKBOC4dfEaUDhMdWqTs/eacDuwptRYeScA
            vIadRz9iQtIxvDSmaCFv+DBmUcZ4Xwqh0RkvIUALZ1RWPgxx23fZWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T17:09:53Z"
    mac: ENC[AES256_GCM,data:v03yf/jlZZCUc6snXJjlMiRl9ysu9G19LuwvtthOg3DZT/zr7bLMYSRSaizJzKN/gOBoKtIGoM6TYAmsVWdzhGDKbK9uw0ujIXlNrWYKk8JJGDI3Mu+jmzLZ/tYKAhJYBS4MxccJ25Xv39G26ehIm5e87ZSNtKVzf9tICUE7vPk=,iv:29+C87RjPVumZx8uucUseOuqJ2BV9uLPV2aBLMG1a6s=,tag:d0z1JJplwMXoo2YLyg3Dyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
