---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-monitoring
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/hlcl1/apps/monitoring/chart
  prune: true
  wait: true
  dependsOn:
    - name: infra-longhorn
    - name: infra-metallb
    - name: infra-nfs-config
    - name: infra-external-secrets-config
