apiVersion: v1
kind: Secret
metadata:
    name: openbao-approle
    namespace: external-secrets
type: Opaque
stringData:
    secret-id: ENC[AES256_GCM,data:EZdcwt7FZw42cnojvMPTR4bpGwSd5+p/EfJQ99VoP6GVU45A,iv:mkJMcMa2LHsK9JEmp5qk4QN+TuX9Wp1rdEbzHhIpAuw=,tag:rPPLT9wssrQE2JPh7jLWlg==,type:str]
sops:
    age:
        - recipient: age1yvyefwwh6avrzpkz2vr3w86ly6q97hdpz02jns2yvaafnjnv448s7jdx7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVWxSc3d5SWNXVW1hN2ZQ
            Zk5nN1ZBR3Z0TDh6eXJ5bGxGdjlTekdJZUYwCjFlYXk0UVZWdW1pZ0w5OWhkdS9h
            MStIVWxsMThwZlNUano1N2dpSEtHcDgKLS0tIFlxSHZzRktGamFKTFdCWUZDVW90
            em9tQlRrVk5NbFRId1pwT1JuNVRxSlkKiFycNUvtP5m3FNXt4U58+T2KAe6e9Z51
            hvbAjo90KRJjg1APIIt7OJ2Jx7cZAOJZH2LDKoK/IdFuIRaRpzWC9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T06:44:35Z"
    mac: ENC[AES256_GCM,data:x+dRZgandk/VVOgxTUH39J0Nt/mc75jB0LaaYBzK3I/52zl4khJu6nlx2qDN7D9b09J38uwjEGH7b6Cn/MX7w/5L4KypGfHZx6GcEBMAoqo53Uy1CyJdZ47Ud0fa4haR4fyTdDfqJfQgcw+AUjGSdAIA704nANCLeygCjFz2N0I=,iv:x7Qgv9Zc0F2twYnBI2CRXWqA1AkX/OvMM15yUJhECtQ=,tag:IbAzdA2v0hBw45I+GrkGhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
