apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ff-postgres
  namespace: ff-production
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    size: 10Gi

  postgresql:
    parameters:
      timezone: UTC

  bootstrap:
    initdb:
      database: flockfeed
      owner: flockfeed
